services:
  subscription:
    build: .
    ports:
      - ${HTTP_PORT}:8080
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./logs:/subscription/logs
    restart: unless-stopped

  db:
    image: postgres:17.6
    container_name: subscription_db
    command:
      - postgres
      - -c
      - port=${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data: